spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/product/**
            
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/user/**
            
        - id: employee-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/employee/**
          filters:
            - AuthFilter

        - id: department-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/department/**
          filters:
            - AuthFilter

        - id: account-service
          uri: http://localhost:8085
          predicates:
            - Path=/auth/**
      